# Generated by Django 5.1.3 on 2024-12-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='available',
            field=models.TextField(default='available'),
        ),
    ]
