# Generated by Django 5.1.3 on 2024-12-01 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legs', '0002_table_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='table', max_length=50),
        ),
        migrations.AddField(
            model_name='table',
            name='number',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=1000000),
        ),
        migrations.AlterField(
            model_name='table',
            name='available',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='table',
            name='color',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('RED', 'RED'), ('GREEN', 'GREEN')], default='BLACK', max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='legs',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='4', max_length=2),
        ),
        migrations.AlterField(
            model_name='table',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=1000000),
        ),
    ]
