# Generated by Django 5.1.3 on 2024-12-02 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('legs', '0003_table_name_table_number_alter_table_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='number',
        ),
    ]
