# Generated by Django 5.1.3 on 2024-12-03 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legs', '0004_remove_table_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='color',
            field=models.CharField(choices=[('BLACK', 'BLACK'), ('WHITE', 'WHITE'), ('RED', 'RED'), ('GREEN', 'GREEN')], max_length=10),
        ),
        migrations.AlterField(
            model_name='table',
            name='legs',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], max_length=2),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
